apiVersion: v1
kind: Service
metadata: # kpt-merge: ingress-nginx/ingress-nginx-controller
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.3.0
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|ingress-nginx|ingress-nginx-controller'
spec:
  externalTrafficPolicy: Local
  ports:
  - appProtocol: ttp
    name: sctp
    port: 5242
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: xeys
    protocol: TCP
    targetPort: fff
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingrdsffsfdsfsess-nginx
  type: LoadBalancer
